;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        down-list
        forward-sexp
        helm-confirm-and-exit-minibuffer
        kill-region
        kill-sexp
        np/join-next-line
        org-delete-char
        org-self-insert-command
        paredit-backward
        paredit-backward-kill-word
        paredit-backward-slurp-sexp
        paredit-close-round-and-newline
        paredit-doublequote
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-semicolon
        paredit-splice-sexp-killing-backward
        paredit-wrap-round
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        rebase-mode-squash
        save-some-buffers
        smart-line-beginning
        sp-remove-active-pair-overlay
        undefined
        wgrep-finish-edit
        what-cursor-position
        yas-expand
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        abort-recursive-edit
        goto-line
        handle-switch-frame
        helm-M-x
        ))
