;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        kill-region
        org-delete-char
        org-self-insert-command
        paredit-backward
        paredit-backward-kill-word
        paredit-backward-slurp-sexp
        paredit-close-round-and-newline
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-open-round
        paredit-semicolon
        paredit-splice-sexp-killing-backward
        paredit-wrap-round
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
